language: node_js

node_js:
  - 10
  - node

before_install:
  - chmod +x coverage_run.sh

before_script:
  - npm install
  - npm install -g codecov

script:
  - make lint
  - make test
  - ./coverage_run.sh

after_success:
  - codecov
